package view;

import dao.ClienteDAO;
import dao.FuncionarioDAO;
import dao.VisitaDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Funcionario;
import model.Visita;

public class VisitasProgramadas extends javax.swing.JFrame {

    private final ClienteDAO cdao = new ClienteDAO();
    private final FuncionarioDAO fdao = new FuncionarioDAO();
    private Visita v = new Visita();
    private Cliente c = new Cliente();
    private Funcionario f;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    
    public VisitasProgramadas(Visita v) {
        initComponents();
        
        this.v = v;
        c = cdao.getClienteId(v.getFkIdCliente());
        f = fdao.getFuncionarioId(v.getFkIdFuncionario());
        
        cmbCliente.addItem(c.getCpf());
        fdao.getFuncionariosLogin(cmbFuncionario);
        cmbFuncionario.setSelectedItem(f.getLogin());
        try {
            dchDataPrevista.setDate(sdf.parse(v.getData()));
        } catch (ParseException ex) {
            Logger.getLogger(VisitasProgramadas.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtObservacao.setText(v.getDetalhes());
        
        if(this.v.getConcluido().equals("S")) {
            rbnSim.setSelected(true);
        } else {
            rbnNao.setSelected(true);
        }
        HistoricoVisitas.visitasDialog.setTitle("Editar visita");
    }
    
    public VisitasProgramadas() {
        initComponents();
        cdao.getClientesCPF(cmbCliente);
        fdao.getFuncionariosLogin(cmbFuncionario);
        HistoricoVisitas.visitasDialog.setTitle("Agendar visita");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblCliente = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        lblDataPrevista = new javax.swing.JLabel();
        lblFuncionario = new javax.swing.JLabel();
        cmbFuncionario = new javax.swing.JComboBox<>();
        lblConcluido = new javax.swing.JLabel();
        rbnSim = new javax.swing.JRadioButton();
        rbnNao = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        btnSalvar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        dchDataPrevista = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agendar visitas");
        setResizable(false);

        lblCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCliente.setText("Cliente:");

        cmbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClienteActionPerformed(evt);
            }
        });

        lblDataPrevista.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDataPrevista.setText("Data prevista:");

        lblFuncionario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFuncionario.setText("Funcionario responsável:");

        lblConcluido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblConcluido.setText("Concluido?");

        buttonGroup1.add(rbnSim);
        rbnSim.setText("S");
        rbnSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnSimActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbnNao);
        rbnNao.setText("N");
        rbnNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnNaoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Observações:");

        txtObservacao.setColumns(20);
        txtObservacao.setRows(5);
        jScrollPane1.setViewportView(txtObservacao);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar.png"))); // NOI18N
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/no.png"))); // NOI18N
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        dchDataPrevista.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(lblConcluido)
                    .addComponent(lblFuncionario)
                    .addComponent(lblDataPrevista)
                    .addComponent(lblCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbnSim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbnNao))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(dchDataPrevista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbCliente, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbFuncionario, javax.swing.GroupLayout.Alignment.LEADING, 0, 140, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDataPrevista)
                    .addComponent(dchDataPrevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncionario)
                    .addComponent(cmbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConcluido)
                    .addComponent(rbnSim)
                    .addComponent(rbnNao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClienteActionPerformed
        
    }//GEN-LAST:event_cmbClienteActionPerformed

    private void rbnSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnSimActionPerformed
        v.setConcluido("S");
    }//GEN-LAST:event_rbnSimActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(verificarCampos()) {
            VisitaDAO vdao = new VisitaDAO();
            c.setCpf(cmbCliente.getSelectedItem().toString());
            v.setData(sdf.format(dchDataPrevista.getDate()));
            v.setDetalhes(txtObservacao.getText());
            if(v.getId() <= 0) {
                c = cdao.getClienteCPF(c);
                v.setFkIdCliente(c.getId());
                f = fdao.getFuncionarioLogin(cmbFuncionario.getSelectedItem().toString());
                v.setFkIdFuncionario(f.getId());
            }
            vdao.salvar(v);
            limparCampos();
            HistoricoVisitas.visitasDialog.dispose();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Todos os campos são obrigatórios!!");
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void rbnNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnNaoActionPerformed
        v.setConcluido("N");
    }//GEN-LAST:event_rbnNaoActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        HistoricoVisitas.visitasDialog.dispose();
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    public void limparCampos() {
        dchDataPrevista.cleanup();
        buttonGroup1.clearSelection();
        txtObservacao.setText(null);
    }
    
    public boolean verificarCampos() {
        boolean podeSalvar = true;

        try {
            
            if (buttonGroup1.getSelection().isSelected()) {
                podeSalvar = true;
            }
            if (cmbCliente.getSelectedItem().toString().isEmpty()) {
                podeSalvar = false;
            }
            if (cmbFuncionario.getSelectedItem().toString().isEmpty()) {
                podeSalvar = false;
            }
            if (dchDataPrevista.getDate().toString().isEmpty()) {
                podeSalvar = false;
            }

        } catch(NullPointerException e) {
            podeSalvar = false;
        }
        return podeSalvar;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisitasProgramadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisitasProgramadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisitasProgramadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisitasProgramadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisitasProgramadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JComboBox<String> cmbFuncionario;
    private com.toedter.calendar.JDateChooser dchDataPrevista;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblConcluido;
    private javax.swing.JLabel lblDataPrevista;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JRadioButton rbnNao;
    private javax.swing.JRadioButton rbnSim;
    private javax.swing.JTextArea txtObservacao;
    // End of variables declaration//GEN-END:variables
}
